<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="tracer_castor">

    <xacro:macro name="fl_castor" params="wheel_prefix *joint_pose">
        <link name="${wheel_prefix}_link">
            <inertial>
                <mass value="1" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
            </inertial>
            <visual>
                   <geometry>
                        <!--<cylinder length="${castor_length}" radius="${castor_radius}"/>-->
                        <mesh filename="package://tracer_description/meshes/castor_joint.dae" />
                   </geometry>
                   <!--<material name="black">
                        <color rgba="255 255 255 1"/>
                   </material>-->
            </visual>
            <!--<collision>
              <origin
                xyz="0 0 0"
                rpy="0 0 0" />
              <geometry>
                <cylinder length="${castor_length}" radius="${castor_radius}"/>
                <mesh filename="package://tracer_description/meshes/castor_joint.dae" />
              </geometry>
            </collision>-->
        </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
            <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0680886}" rpy="-1.57 0 0" />
            <parent link="base_link" />
            <child link="fl_castor_link" />
            <axis xyz="0 1 0" rpy="0 0 0" />
        </joint>
        </xacro:macro>

    </robot>
