<?xml version="1.0"?>

<robot name="tracer_v1"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_1.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_2.xacro" />

    <xacro:include filename="$(find tracer_description)/urdf/fr_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/fl_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rr_castor.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rl_castor.xacro" />

    <xacro:include filename="$(find tracer_description)/urdf/fr_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/fl_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rr_wheel.xacro" />
    <xacro:include filename="$(find tracer_description)/urdf/rl_wheel.xacro" />



    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.34"/><!--0.33515-->
    <xacro:property name="track" value="0.37910" /><!--0.37810-->

    <xacro:property name="castor_length" value="0.002"/>
    <xacro:property name="castor_radius" value="0.03724" />

  <!-- <xacro:property name="wheel_vertical_offset" value="-0.0777463" />-->
  <!--<xacro:property name="wheel_vertical_offset" value="-0.0749083" />-->
  <xacro:property name="wheel_vertical_offset" value="-0.082" />
  <xacro:property name="castor_offset" value="0.03" />

<!--    <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" />-->

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
            <geometry>
                <mesh filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
                 <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
            </geometry>
        </visual>
        <collision>
          <!--origin
            xyz="-0.0145261552504705 0.0231316650320557 0.00586280190939592"
            rpy="0 0 0" /-->
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
          <geometry>
            <mesh
              filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
              <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
          </geometry>
        </collision>
    </link>

    <!-- <joint name="chassis_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint> -->

    <link name="inertial_link">
        <inertial>
            <!--mass value="44.3898489950015" /-->
            <mass value="132.3898489950015" />
            <!-- <mass value="50" /> -->
            <!-- <origin xyz="-0.00065 -0.085 0.062" />
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
            <origin xyz="0.015 0.0231316650320557 0" />
            <!--<origin
              xyz="-0.0145261552504705 0.0231316650320557 0.00586280190939592"
              rpy="0 0 0" />-->
            <inertia ixx="0.185196122711036"
            ixy="4.30144213829512E-08"
            ixz="5.81037523686401E-08"
            iyy="0.364893736238929"
            iyz="-0.000386720198091934"
            izz="0.223868521722778" />
            <!--<inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />-->
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->

    <!-- tracer wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:tracer_wheel_1 wheel_prefix="right">
        <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:tracer_wheel_1>
    <xacro:tracer_wheel_2 wheel_prefix="left">
        <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:tracer_wheel_2>

<!--tracer castor wheel-->

    <xacro:fl_castor wheel_prefix="fl_castor">
        <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:fl_castor>
    <xacro:fr_castor wheel_prefix="fr_castor">
        <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:fr_castor>
    <xacro:rr_castor wheel_prefix="rr_castor">
        <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:rr_castor>
    <xacro:rl_castor wheel_prefix="rl_castor">
        <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
    </xacro:rl_castor>


    <!--<xacro:fl_wheel wheel_prefix="fl">
        <origin xyz="${track/2} ${wheelbase/2} ${wheel_vertical_offset-0.015}" rpy="1.57 0 0" />
    </xacro:fl_wheel>
    <xacro:fr_wheel wheel_prefix="fr">
        <origin xyz="${track/2} ${-wheelbase/2} ${wheel_vertical_offset-0.015}" rpy="-1.57 0 0" />
    </xacro:fr_wheel>
    <xacro:rr_wheel wheel_prefix="rr">
        <origin xyz="${-track/2} ${-wheelbase/2} ${wheel_vertical_offset-0.015}" rpy="-1.57 0 0" />
    </xacro:rr_wheel>
    <xacro:rl_wheel wheel_prefix="rl">
        <origin xyz="${-track/2} ${wheelbase/2} ${wheel_vertical_offset-0.015}" rpy="1.57 0 0" />
    </xacro:rl_wheel>-->
    <xacro:fl_wheel wheel_prefix="fl">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:fl_wheel>
    <xacro:fr_wheel wheel_prefix="fr">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:fr_wheel>
    <xacro:rr_wheel wheel_prefix="rr">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:rr_wheel>
    <xacro:rl_wheel wheel_prefix="rl">
        <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
    </xacro:rl_wheel>




    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find tracer_description)/urdf/tracer.gazebo" />
</robot>
