# Publish all joint states -----------------------------------
tracer_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint velocity controllers ---------------------------------
tracer_motor_r_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

tracer_motor_l_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

#/gazebo_ros_control/pid_gains:
#right_wheel: {p: 1.0, i: 0, d: 0.01}
#left_wheel: {p: 1.0, i: 0, d: 0.01}
