
/*
 *****************************************************************************
 *                                                                           *
 *                 IMPINJ CONFIDENTIAL AND PROPRIETARY                       *
 *                                                                           *
 * This source code is the sole property of Impinj, Inc.  Reproduction or    *
 * utilization of this source code in whole or in part is forbidden without  *
 * the prior written consent of Impinj, Inc.                                 *
 *                                                                           *
 * (c) Copyright Impinj, Inc. 2007,2008. All rights reserved.                *
 *                                                                           *
 *****************************************************************************/

/**
 *****************************************************************************
 **
 ** @file impinj_ltkcpp.h
 **
 ** @brief  File that includes all Impinj Custom extension classes and types
 **
 ** This file includes all the Impinj custom extension classes and types that
 ** are generated by the LLRP automated build process.
 **
 *****************************************************************************/

#ifndef _IMPINJ_LTKCPP_H
#define _IMPINJ_LTKCPP_H

namespace LLRP
{
#include "out_impinj_ltkcpp.h"
}; /* namespace LLRP */

#endif /* !_IMPINJ_LTKCPP_H */

